production:
  app: mah365-dashing-api
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app: mah365-dashing-api-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
    RAILS_ENV: staging
    RACK_ENV: staging
  addons:
    - heroku-postgresql
    - papertrail
    - newrelic:stark
    - pgbackups:auto-month
    - scheduler

